config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'application#index'

  resources :events do
    resources :tickets
  end

  get "tickets/all"
  get "money/index"

  resources :money
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 30 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :event_date, presence: true
  validates :size, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :image, presence: true
  validate :valid_date?
  has_many :tickets

  def valid_date?
    if event_date.past?
      errors.add(event_date.to_s, "- invalid date, date can not be set in past!");
    end
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  def index
    @title = "Witaj w aplikacji Bilecik"
    @description = "Aplikacja pozwala na zarządzanie wydarzeniami oraz zakup biletów."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:create, :destroy]

  def new

  end

  def index
    @events = Event.all
    puts @events
  end

  def show
    @event = Event.find(params[:id])

    @taken = 0
    @event.tickets.each do |ticket|
      @taken += ticket.places
    end

  end

  def create
    @event = Event.new(params.require(:event).permit(:name, :description, :price, :event_date, :size, :image,
                                                     :for_children))

    if @event.save
      redirect_to @event, notice: "You created new event."
      return
    else
      @error_text = ""
      @event.errors.full_messages.each {|m| @error_text += m + ". "}
      redirect_to new_event_path, alert: @error_text
      return
    end

  end

  def destroy
    if !current_user.is_admin
      redirect_to events_path, alert: "Only administrator can remove events!"
      return
    end

    @event = Event.find(params[:id])
    @event.tickets.each {|t| t.destroy}
    @event.destroy

    redirect_to events_path
  end

  def correct_user
    if !current_user.is_admin
      redirect_to events_path, alert: "Only administrator can perform this action!"
    end
  end

end

app/controllers/money_controller.rb
class MoneyController < ApplicationController
  before_action :authenticate_user!

  def index

  end

  def create
    @user = User.find(current_user.id)
    @user.money += 1000
    @user.save
    redirect_to money_index_path, notice: "New founds have been added to your account."
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:index]

  def index
    @event = Event.find(params[:event_id])
    @tickets = @event.tickets
  end

  def all
    if current_user.is_admin
      @tickets = Ticket.all
    else
      @tickets = current_user.tickets
    end

  end

  def destroy
    if !current_user.is_admin
      @t = current_user.tickets.find(params[:id])

      if @t.event.event_date.past?
        redirect_to tickets_all_path, alert: "You can not remove tickets for events from past."
        return
      end

      if !@t.to_return
        @t.to_return = true
        @t.save
        redirect_to tickets_all_path, notice: "Your ticket has been marked to return."
        return
      else
        redirect_to tickets_all_path, alert: "Your ticket is already marked to return."
        return
      end
    end

    @t = Ticket.find(params[:id])

    if @t.event.event_date.past?
      redirect_to tickets_all_path, alert: "You can not remove tickets for events from past."
      return
    end

    if !@t.to_return
      redirect_to tickets_all_path, alert: "You can not remove this ticket."
      return
    end

    @money = @t.places * @t.event.price * 0.75
    @t.destroy

    @user = User.find(current_user.id)
    @user.money += @money
    @user.save

    redirect_to tickets_all_path, notice: "Ticket has been deleted."
  end

  def create
    @event = Event.find(params[:event_id])

    @params = ticket_params
    @params["event_id"] = params[:event_id]
    @params["user_id"] = current_user.id

    # check if event is not from past
    if @event.event_date.past?
      redirect_to event_path(@event), alert: "You can not buy tickets for events from past!"
      return
    end

    if (@event.event_date - Date.today).to_i > 31
      redirect_to event_path(@event), alert: "You can buy ticket only month before event."
      return
    end

    # check if user has already ticket for this event
    if @event.tickets.exists?(user_id: current_user.id)
      redirect_to event_path(@event), alert: "You already have ticket for this event!"
      return
    end

    @ticket = Ticket.new(@params)

    #check if ticket has valid places number
    if @ticket.places < 1 || @ticket.places > 5
      redirect_to event_path(@event), alert: "Invalid number of places!"
      return
    end

    # check if user has enough money
    if @ticket.places * @event.price > current_user.money
      redirect_to event_path(@event), alert: "You don't have enough money!"
      return
    end

    # check if there are enough places
    @taken = 0
    @event.tickets.each do |ticket|
      @taken += ticket.places
    end

    if @event.size - @taken < @ticket.places
      redirect_to event_path(@event), alert: "There are not enough places left for this event."
      return
    end

    if @ticket.save
      @user = User.find(current_user.id)
      @user.money -= @ticket.places * @event.price
      @user.save
      redirect_to event_path(@event), notice: "You bought new ticket."
      return
    else
      @error_text = ""
      @ticket.errors.full_messages.each {|m| @error_text += m + ". "}
      redirect_to event_path(@event), alert: @error_text
      return
    end
  end

  def ticket_params
    params.require(:ticket).permit(:places)
  end

  def correct_user
    if !current_user.is_admin
      redirect_to events_path, alert: "Only administrator can perform this action!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/money_helper.rb
module MoneyHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/application/index.html.erb
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">
        Welcome in ZPW Ticket App
      </h1>
      <p>
        Application allows you to manage events and tickets.
      </p>
    </div>
  </div>

app/views/events/_ticketFrom.html.erb
<div class="card" style="margin-top: 10px">
  <div class="card-header">
    Buy ticket:
  </div>
  <div class="card-body">
    <%= form_with(model: [ @event, @event.tickets.build ], local: true) do |form| %>
      <div class="form-group row">
        <div class="col-lg-1">
          <%= form.label :places %>
        </div>
        <div class="col-lg-2">
          <%= form.number_field :places %>
        </div>
        <div class="col-lg-1">
          <%= form.submit "Buy ticket", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class="card" style="margin-top: 10px">
    <h5 class="card-header">
      <%= event.name %>
    </h5>
    <div class="card-body">
      <p class="card-text">
        <div class="row">
          <div class="col-lg-4">
            <img src=<%= "#{event.image}" %> alt="" style="max-height: 300px; max-width: 300px;">
          </div>
          <div class="col-lg-8">
            <table class="table">
              <tbody>
              <tr>
                <td>Date:</td>
                <td><%= event.event_date %></td>
              </tr>
              <tr>
                <td>Ticket price:</td>
                <td><%= event.price %></td>
              </tr>
              <tr>
                <td>Number of places:</td>
                <td><%= event.size %></td>
              </tr>
              <tr>
                <td>Available for childred</td>
                <td>
                  <% if(event.for_children) %>
                    <%= "Yes" %>
                  <% else %>
                    <%= "No" %>
                  <% end %>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      <div style="text-align: right; width: 100%">
        <div class="row">
          <div class="col-lg-6" style="text-align: left">
            <% if user_signed_in? && current_user.is_admin %>
              <%= button_to "Delete event", event, :method=>:delete, class: "btn btn-danger" %>
            <% end %>
          </div>
          <div class="col-lg-6">
            <%= link_to 'Details', event_path(event), class:"btn btn-primary", style: "display: inline" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title">Fill form below to add new event:</h5>
    <hr>

    <%= form_with scope: :event, url: events_path, local: true do |form| %>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :name %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :description %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_area :description, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :price %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :price, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :event_date %><br>
        </div>
        <div class="col-lg-10">
          <%= form.date_field :event_date, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :size %><br>
        </div>
        <div class="col-lg-10">
          <%= form.number_field :size, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :for_children %><br>
        </div>
        <div class="col-lg-10">
          <%= form.check_box :for_children %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-lg-2">
          <%= form.label :image %><br>
        </div>
        <div class="col-lg-10">
          <%= form.text_field :image, class: "form-control" %>
        </div>
      </div>



      <p>
        <%= form.submit class: "btn btn-success"%>
      </p>
    <% end %>



  </div>
</div>

app/views/events/show.html.erb
<div class="card">
  <div class="card-header">
    <%=	"#{@event.name}" %>
  </div>
  <img class="card-img-top" src=<%= "#{@event.image}" %>>
  <div class="card-body">
    <p class="card-text">
        <table class="table">
          <tbody>
          <tr>
            <td>Date:</td>
            <td><%= @event.event_date %></td>
          </tr>
          <tr>
            <td>Ticket price:</td>
            <td><%= @event.price %></td>
          </tr>
          <tr>
            <td>Number of places:</td>
            <td><%= @event.size %></td>
          </tr>
          <tr>
            <td>Bought places:</td>
            <td>
              <%= @taken %>
            </td>
          </tr>
          <tr>
            <td>Available for childred</td>
            <td>
              <% if(@event.for_children) %>
                <%= "Yes" %>
              <% else %>
                <%= "no" %>
              <% end %>
            </td>
          </tr>
          </tbody>
        </table>

        <%= @event.description %>
      </p>
    <% if current_user.is_admin %>
      <hr>
      <%= link_to 'See tickets bought for this event', event_tickets_path(@event), class:"btn btn-info", style: "display: inline" %>
    <% end %>
    </div>
</div>

<% if user_signed_in? %>
  <% if @event.tickets.exists?(user_id: current_user.id) %>
    <div class="card" style="margin-top: 10px">
      <div class="card-body">
        You have already bought ticket to this event.
      </div>
    </div>
  <% else if @event.event_date.past? %>
      <div class="card" style="margin-top: 10px">
        <div class="card-body">
          You can not buy tickets for events from past!
        </div>
      </div>
    <% else if (@event.event_date - Date.today).to_i > 31 %>
        <div class="card" style="margin-top: 10px">
          <div class="card-body">
            You can buy ticket only month before event.
          </div>
        </div>
  <% else %>
    <%= render 'events/ticketFrom' %>
  <% end %>
<% end %>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to 'Events list', events_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <% if current_user.is_admin %>
          <li>
            <%= link_to 'Add new event', new_event_path, class: "nav-link" %>
          </li>
        <% end %>
        <li>
          <%= link_to 'Tickets', tickets_all_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to 'My money', money_index_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <span class="navbar-text">
      <% if user_signed_in? %>
        <% if current_user.is_admin %>
          Logged in as <strong>Administrator</strong>.
        <% else %>
          Logged in as <strong><%= current_user.email %></strong>.
        <% end %>

        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
      <% end %>
    </span>
  </div>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZpwBilecik</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container" style="margin-top: 10px; margin-bottom: 10px">
      <%= yield %>
    </div>

  </body>
</html>

app/views/money/index.html.erb
<div class="card">
  <div class="card-body">
    Your account balance: <%= current_user.money %>
    <hr>

    <%= link_to 'Add 1000 to your account', "/money", method: "post",class: "btn btn-success" %>

  </div>
</div>

app/views/tickets/all.html.erb
<% @tickets.each do |ticket| %>
  <div class="card" style="margin-bottom: 10px">
    <div class="card-body">
      <% if current_user.is_admin %>
        <div class="row">
          <div class="col-6">
            <b>Owner of ticket:</b> <%= ticket.user.email %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-3">
          <b>Event:</b> <%= ticket.event.name %>
        </div>
        <div class="col-2">
          <b>Date:</b> <%= ticket.event.event_date %>
        </div>
        <div class="col-2">
          <b>Places:</b> <%= ticket.places %>
        </div>
        <div class="col-2">
          <b>Price:</b> <%= ticket.places * ticket.event.price %>
        </div>
        <div class="col-3" style="text-align: right">
          <% if ticket.event.event_date.past? %>
            <button type="button" class="btn btn-secondary">
              Event time passed.
            </button>
          <% else %>
            <% if current_user.is_admin %>
              <% if ticket.to_return %>
                <a href=<%= "/events/#{ticket.event.id}/tickets/#{ticket.id}" %> class="btn btn-warning btn-sm" role="button" data-method="delete" aria-disabled="true">Accept ticket return</a>
              <% else %>
                <button type="button" class="btn btn-secondary btn-sm">No action available</button>
              <% end %>
            <% else %>
              <% if !ticket.to_return %>
                <a href=<%= "/events/#{ticket.event.id}/tickets/#{ticket.id}" %> class="btn btn-warning btn-sm" role="button" data-method="delete" aria-disabled="true">Return ticket</a>
              <% else %>
                <button type="button" class="btn btn-secondary btn-sm">Wait for administrator action.</button>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/tickets/index.html.erb
<% @tickets.each do |ticket| %>
  <div class="card" style="margin-bottom: 10px">
    <div class="card-body">


      <div class="row">
        <div class="col-6">
          <b>Owner of ticket:</b> <%= ticket.user.email %>
        </div>
        <div class="col-3">
          <b>Places:</b> <%= ticket.places %>
        </div>
        <div class="col-#">
          <b>Price:</b> <%= ticket.places * ticket.event.price %>
        </div>
      </div>
    </div>
  </div>

<% end %>